In [1]:
# imports
import torch
from modules.myFunctions import set_device, test_model


In [2]:


# Load the test dataset
dataset_path = "../storage/images/apple_resized_128/Test"

# import the model state
imported_model_state_path = "../storage/data/generated/20230613-153713_pinky_loss.pt"   # test to 224x224 accuracy

# set the device
device = set_device() 

# import the model
model = torch.load(imported_model_state_path)


test_model(model, dataset_path, device)

Device is 'mps' Thus a tensor will look like this: tensor([1.], device='mps:0')


/Users/stephandekker/.local/share/virtualenvs/pink_lady-bMzUwwsu/lib/python3.11/site-packages/torchvision/transforms/functional.py:1603: UserWarning: The default value of the antialias parameter of all the resizing transforms (Resize(), RandomResizedCrop(), etc.) will change from None to True in v0.17, in order to be consistent across the PIL and Tensor backends. To suppress this warning, directly pass antialias=True (recommended, future default), antialias=None (current default, which means False for Tensors and True for PIL), or antialias=False (only works on Tensors - PIL will still use antialiasing). This also applies if you are using the inference transforms from the models weights: update the call to weights.transforms(antialias=True).
  warnings.warn(


Overall accuracy: 0.6562
Normal Apple accuracy: 0.5000
Abnormal Apple accuracy: 0.7083

{'Blotch_Apple': 0, 'Normal_Apple': 1, 'Rot_Apple': 2, 'Scab_Apple': 3}
Confusion Matrix:
[[11  0  0  0]
 [ 1  4  0  3]
 [ 3  1  2  2]
 [ 1  0  0  4]]
From a lot of 500 in accordance quality level I,
a batch of 32 has been randomly drawn.
the number of rejected apples is: 24
The AQL label is: Class_Rejected
